# Generated by Django 6.0.5 on 2026-05-13 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pigeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bague', models.CharField(max_length=50, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1)),
                ('race', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('vendu', 'Vendu'), ('mort', 'Mort'), ('perdu', 'Perdu')], default='actif', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_female', models.ForeignKey(blank=True, limit_choices_to={'sex': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='api.pigeon')),
                ('parent_male', models.ForeignKey(blank=True, limit_choices_to={'sex': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='api.pigeon')),
            ],
        ),
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formed_at', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('dissolved_at', models.DateField(blank=True, null=True)),
                ('female', models.ForeignKey(limit_choices_to={'sex': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='couples_as_female', to='api.pigeon')),
                ('male', models.ForeignKey(limit_choices_to={'sex': 'M'}, on_delete=django.db.models.deletion.CASCADE, related_name='couples_as_male', to='api.pigeon')),
            ],
        ),
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('couple', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cage', to='api.couple')),
                ('pigeon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cage', to='api.pigeon')),
            ],
        ),
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pond_date', models.DateField()),
                ('hatch_date', models.DateField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('babies', models.ManyToManyField(blank=True, related_name='from_reproduction', to='api.pigeon')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductions', to='api.couple')),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vente', 'Vente'), ('deces', 'Décès'), ('perte', 'Perte')], max_length=10)),
                ('date', models.DateField()),
                ('buyer', models.CharField(blank=True, default='', max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('pigeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorties', to='api.pigeon')),
            ],
        ),
    ]
