# Generated by Django 6.0.5 on 2026-05-14 13:14

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formed_at', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('dissolved_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('user_type', models.CharField(choices=[('admin', 'admin'), ('superadmin', 'superadmin'), ('deleted', 'deleted')], default='admin', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pigeon_assigned', 'Pigeon affecté'), ('pigeon_removed', 'Pigeon retiré de la cage'), ('couple_assigned', 'Couple affecté'), ('couple_removed', 'Couple retiré de la cage'), ('cage_cleaned', 'Cage nettoyée'), ('health_check', 'Contrôle sanitaire')], max_length=32)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.cage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cage',
            name='couple',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cage', to='api.couple'),
        ),
        migrations.CreateModel(
            name='Pigeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bague', models.CharField(max_length=50, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1)),
                ('race', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('vendu', 'Vendu'), ('mort', 'Mort'), ('perdu', 'Perdu')], default='actif', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_female', models.ForeignKey(blank=True, limit_choices_to={'sex': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='api.pigeon')),
                ('parent_male', models.ForeignKey(blank=True, limit_choices_to={'sex': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='api.pigeon')),
            ],
        ),
        migrations.AddField(
            model_name='couple',
            name='female',
            field=models.ForeignKey(limit_choices_to={'sex': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='couples_as_female', to='api.pigeon'),
        ),
        migrations.AddField(
            model_name='couple',
            name='male',
            field=models.ForeignKey(limit_choices_to={'sex': 'M'}, on_delete=django.db.models.deletion.CASCADE, related_name='couples_as_male', to='api.pigeon'),
        ),
        migrations.AddField(
            model_name='cage',
            name='pigeon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cage', to='api.pigeon'),
        ),
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pond_date', models.DateField()),
                ('hatch_date', models.DateField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('babies', models.ManyToManyField(blank=True, related_name='from_reproduction', to='api.pigeon')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductions', to='api.couple')),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vente', 'Vente'), ('deces', 'Décès'), ('perte', 'Perte')], max_length=10)),
                ('date', models.DateField()),
                ('buyer', models.CharField(blank=True, default='', max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('pigeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorties', to='api.pigeon')),
            ],
        ),
    ]
