# Generated by Django 6.0.1 on 2026-05-19 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couple',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='couples/'),
        ),
        migrations.AddField(
            model_name='couple',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pigeon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pigeons/'),
        ),
        migrations.AddField(
            model_name='pigeon',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pigeons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reproduction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reproductions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sortie',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sorties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cage',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='bague',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='cage',
            unique_together={('user', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='pigeon',
            unique_together={('user', 'bague')},
        ),
    ]
